spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bsm_db?createDatabaseIfNotExist=true
        username: root
        password: akash
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    logging:
        level:
            org.springframework.web: DEBUG # Enables debug logging for Spring Web
            root: INFO                    # Sets the default log level for the application
